# Generated by Django 4.2 on 2023-04-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
